import { Aside } from '@/components/aside/aside/aside.component'
import { CallToAction } from '@/components/call-to-action/call-to-action.component'
import { Post } from '@/components/cards/post/post.component'
import { LayoutPage } from '@/components/layouts/layout-page/layout-page.component'
import { LayoutPosts } from '@/components/layouts/layout-posts/layout-posts.component'
import { Pagination } from '@/components/pagination/pagination.component'
import { GetStaticPaths, GetStaticProps, GetStaticPropsContext } from 'next'

function Blog() {
    return (
        <LayoutPage
            meta={{
                title: "Create Next App",
                description: "Generated by create next app"
            }}
        >
            <CallToAction
                preview='https://wallpaperaccess.com/full/1308942.png'
                title='OUR RECENT BLOG ENTRIES'
                subtile='RECENT POSTS'
                classes={{
                    root: "call-to-action_size"
                }}
                full
            />
            <LayoutPosts
                sidebar={<Aside />}
                footer={
                    <Pagination count={100} onChange={() => { }} page={1} />}
            >
                {
                    [1, 2, 3].map((item) => (
                        <div className="col-lg-6" key={item}>
                            <Post small />
                        </div>
                    ))
                }
            </LayoutPosts>
        </LayoutPage>
    )
}

/*
export const getStaticProps: GetStaticProps = async ({
    params,
}: GetStaticPropsContext) => {
    const page = Number(params?.page) || 1
    const { products = [], total = 0 } = {}

    if (!products.length) {
        return {
            notFound: true,
        }
    }

    return {
        props: {
            products: [],
            totalProducts: 0,
            currentPage: page,
        },
        revalidate: 60 * 60 * 24,
    }
}

export const getStaticPaths: GetStaticPaths = async () => {
    return {
        paths: Array.from({ length: 5 }).map((_, i) => `/blog/${i + 2}`),
        fallback: 'blocking',
    }
}
*/
export default Blog;