import { CallToAction } from '@/components/call-to-action/call-to-action.component'
import { LayoutPage } from '@/components/layouts/layout-page/layout-page.component'
import Image from 'next/image'

export default function About() {
    return (
        <LayoutPage
            meta={{
                title: "About",
                description: "Generated by create next app"
            }}
        >
            <CallToAction
                preview='https://wallpaperaccess.com/full/1308942.png'
                title='OUR RECENT BLOG ENTRIES'
                subtile='RECENT POSTS'
                classes={{
                    root: "call-to-action_size"
                }}
                full
            />

        </LayoutPage>
    )
}
