import { Aside } from '@/components/aside/aside/aside.component'
import { CallToAction } from '@/components/call-to-action/call-to-action.component'
import { Post } from '@/components/cards/post/post.component'
import { LayoutPage } from '@/components/layouts/layout-page/layout-page.component'
import { LayoutPosts } from '@/components/layouts/layout-posts/layout-posts.component'
import { PostSlider } from '@/components/post-slider/post-slider.component'

export default function Home() {
  return (
    <LayoutPage
      meta={{
        title: "Create Next App",
        description: "Generated by create next app"
      }}
    >
      <PostSlider />
      <div className='box-100' />
      <CallToAction preview='https://wallpaperaccess.com/full/1308942.png' title='Creative HTML Template For Bloggers!' subtile='Stand Blog HTML5 Template' link={{
        label: "Download Now!",
        onClick: () => { }
      }} />
      <LayoutPosts
        sidebar={<Aside />}
      >
        <div className="col-lg-12">
          <Post />
        </div>
      </LayoutPosts>
    </LayoutPage>
  )
}
